"use client";

import localFont from "next/font/local";
import "./globals.css";
import * as React from "react";
import { useEffect } from "react";
import LayoutComponent from "./component/_commons/layout";
import ApolloUploadSetting from "@/commons/settings/apollo-upload-setting";
import ApolloHeaderSetting from "@/commons/settings/apollo-header-setting";
import { useRouter } from "next/navigation";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ApolloHeaderSetting>
          <div></div>
          <LayoutComponent>{children}</LayoutComponent>
          <div></div>
        </ApolloHeaderSetting>
      </body>
    </html>
  );
}
