import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendardBold = localFont({
  src: "./fonts/Pretendard-Bold.woff",
  variable: "--font-bold",
  weight: "100 900",
});

const pretendardMedium = localFont({
  src: "./fonts/Pretendard-Medium.woff",
  variable: "--font-medium",
  weight: "100 900",
});

const pretendardThin = localFont({
  src: "./fonts/Pretendard-Thin.woff",
  variable: "--font-thin",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="ko">
      <body>
        {props.children}
      </body>
    </html>
  );
}

// export default function Input ({label, type, id, placeholder, name, onChange} : Props) {
//   const aaa: string = `css_${name}input`
//   console.log(aaa)
//   console.log(`스타일 태그: ${styles.[aaa]}`)
//   console.log(`스타일 태그: ${styles.css_password}`)
//   return (
//   <div>
//     <label htmlFor={name} className={`css_${name}tag`}>{label}</label>
//     <input type={type} id={id} name={name} placeholder={placeholder} className={styles.aaa} onChange={onChange}/>
//   </div>
//   );
// };