import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import ReduxProviders from "@/components/reduxProvider";
import { Noto_Sans_KR, Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSansKr = Noto_Sans_KR({
  preload: false,
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--noto-sans-kr",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`antialiased`}>
        <Header></Header>
        <div className="max-w-7xl m-auto py-10 max-xl:max-w-full max-xl:mx-5 flex flex-col gap-10">
          <ReduxProviders>{children}</ReduxProviders>
        </div>
      </body>
    </html>
  );
}
