import type { Metadata } from "next";
import "./globals.css";
import ApolloSetting from "../commons/settings/apollo-setting";
import { Noto_Sans_KR, Roboto } from "next/font/google";
import ThemeProvider from "@/components/themeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const notoSansKr = Noto_Sans_KR({
  preload: false,
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--noto-sans-kr",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`antialiased ${notoSansKr.variable} ${roboto.variable} dark:bg-[#141414]`}
      >
        <ApolloSetting>
          <AntdRegistry>
            <ThemeProvider>{children}</ThemeProvider>
          </AntdRegistry>
        </ApolloSetting>
      </body>
    </html>
  );
}
