import "./globals.css";
import { Inter } from "next/font/google";
import ApolloSetting from "commons/settings/apollo-setting";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <ApolloSetting>
        <body className={inter.className}>{children}</body>
      </ApolloSetting>
    </html>
  );
}
