import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import PageLayout from "@/common/layout/layout";

const pretendard = localFont({
    src: "../styled-system/fonts/PretendardVariable.woff2",
    variable: "--font-pre-var",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ko">
            <body className={`${pretendard.variable}`}>
                <PageLayout>{children}</PageLayout>
            </body>
        </html>
    );
}
