import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { css } from "@/styled-system/css";

const pretendard = localFont({
    src: "../styled-system/fonts/PretendardVariable.woff2",
    variable: "--font-pre-var",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${pretendard.variable}`}>
                <main className={app}>{children}</main>
            </body>
        </html>
    );
}

const app = css({
    minW: "32rem",
    minH: "100vh",

    w: "100vw",
    bg: "#fefefe",

    p: "2rem",
    boxShadow: "0px 4px 8px #bbb",
});
