import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import ApolloSetting from "@/commons/apollo-setting";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "개인프로젝트 화면",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html>
      <body>
        <ApolloSetting>
          <div>{props.children}</div>
        </ApolloSetting>
      </body>
    </html>
  );
}
