version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${PORT}:${PORT}'
        env_file: .env.development
        depends_on:
            - postgres
            - mongo
            - redis
        networks:
            - my_network

    postgres:
        image: postgres:14
        environment:
            POSTGRES_USER: ${POSTGRE_DB_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRE_DB_PASSWORD}
            POSTGRES_DB: ${POSTGRE_DB_DATABASE}
        ports:
            - '${POSTGRE_DB_PORT}:${POSTGRE_DB_PORT}'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - my_network

    mongo:
        image: mongo:5.0
        ports:
            - '${MONGO_DB_PORT}:${MONGO_DB_PORT}'
        volumes:
            - mongo-data:/data/db
        networks:
            - my_network

    redis:
        image: redis:6-alpine
        ports:
            - '6379:6379'
        networks:
            - my_network

volumes:
    postgres-data:
    mongo-data:

networks:
    my_network:
