// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body>
        <div>=====여기위는 레이아웃입니다.=======</div>
        {props.children}
        <div>=====여기아래는 레이아웃입니다.=======</div>
      </body>
    </html>
  );
}

/*
[ Next 실행 순서 ]
1.주소창에 주소 입력
  => http://localhost:3000/
2.입력된 주소의 폴더안에 page.tsx 찾기
  => app/page.tsx
    (ex. 주소: /mypage 라면 app/mypage/page.tsx)
3. 해당 페이지컴포넌트를 통째로 props에 넣어서 실행하기
<RootLayout children={페이지컴포넌트}/>
*/