import "./globals.css";
import { Inter } from "next/font/google";
import ApolloSetting from "commons/settings/apollo-setting";
import { Metadata } from "next";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: 'backdevjung', url: 'http://localhost:3000' }],
  robots: 'index, follow'
};

//export const runtime = 'edge';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  
  const viewPort = [
    "width=device-width",
    "initial-scale=1"
  ].join(", ");
  
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content={viewPort} />
      </head>
      <ApolloSetting>
        <body className={inter.className}>{children}</body>
      </ApolloSetting>
    </html>
  );
}