import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import ApolloSetting from "commons/settings/apollo-setting";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const 글로벌폰트 = localFont({
  src: "./fonts/Pretendard-Regular.woff2",
  variable: "--글로벌폰트",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <ApolloSetting>
        <body className={`${글로벌폰트.variable}`}>{children}</body>
      </ApolloSetting>
    </html>
  );
}
