import type { Metadata } from "next";
import localFont from "next/font/local";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localFontSet = localFont({
  variable: "--suit",
  src: "./fonts/SUIT-Variable.woff2",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <AntdRegistry>
        <body className={`${localFontSet.variable} antialiased`}>
          {children}
        </body>
      </AntdRegistry>
    </html>
  );
}
