overwrite: true
schema: 'http://172.16.2.165:8080/graphql'
documents: 'src/graphql/**/*.graphql'

generates:
    src/generated/graphql.ts:
        plugins:
            - 'typescript'
            - 'typescript-resolvers'
config:
    scalars:
        DateTime:
            input: string
            output: string
