import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Layout from "@/commons/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localFontSet = localFont({
  variable: "--suit",
  src: "./fonts/SUIT-Variable.woff2",
});

interface IChildrenType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IChildrenType) {
  return (
    <html lang="ko">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body className={`${localFontSet.variable} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
