# GitHub Actions Workflow
name: Deploy Server

on:
    push:
        branches:
            - server

jobs:
    deploy-server:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to EC2
              env:
                  HOST: ${{ secrets.EC2_HOST }}
                  USER: ${{ secrets.EC2_USER }}
                  SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
                  ENV_FILE: .env.production # Production 환경 파일 지정
              run: |
                  ssh -o StrictHostKeyChecking=no -i $SSH_KEY $USER@$HOST << 'EOF'
                    cd /server
                    docker-compose -f docker-compose.prod.yml down || true
                    docker-compose -f docker-compose.prod.yml up -d --build
                  EOF
